// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDNSServer(arg1) {
  return window['go']['main']['App']['AddDNSServer'](arg1);
}

export function AddInbound(arg1) {
  return window['go']['main']['App']['AddInbound'](arg1);
}

export function AddNode(arg1) {
  return window['go']['main']['App']['AddNode'](arg1);
}

export function AddRoutingRule(arg1) {
  return window['go']['main']['App']['AddRoutingRule'](arg1);
}

export function ClearCoreLogs() {
  return window['go']['main']['App']['ClearCoreLogs']();
}

export function CopyLogs(arg1) {
  return window['go']['main']['App']['CopyLogs'](arg1);
}

export function DeleteInbound(arg1) {
  return window['go']['main']['App']['DeleteInbound'](arg1);
}

export function DeleteNode(arg1) {
  return window['go']['main']['App']['DeleteNode'](arg1);
}

export function DeleteRoutingRule(arg1) {
  return window['go']['main']['App']['DeleteRoutingRule'](arg1);
}

export function DisableProxy() {
  return window['go']['main']['App']['DisableProxy']();
}

export function DownloadKernel(arg1) {
  return window['go']['main']['App']['DownloadKernel'](arg1);
}

export function EnableProxy() {
  return window['go']['main']['App']['EnableProxy']();
}

export function GenerateQRCode(arg1) {
  return window['go']['main']['App']['GenerateQRCode'](arg1);
}

export function GetActiveNodeID() {
  return window['go']['main']['App']['GetActiveNodeID']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetCoreLogs(arg1) {
  return window['go']['main']['App']['GetCoreLogs'](arg1);
}

export function GetCoreStatus() {
  return window['go']['main']['App']['GetCoreStatus']();
}

export function GetCoreUptime() {
  return window['go']['main']['App']['GetCoreUptime']();
}

export function GetDNSConfig() {
  return window['go']['main']['App']['GetDNSConfig']();
}

export function GetFilteredLogs(arg1, arg2) {
  return window['go']['main']['App']['GetFilteredLogs'](arg1, arg2);
}

export function GetGroups() {
  return window['go']['main']['App']['GetGroups']();
}

export function GetInbounds() {
  return window['go']['main']['App']['GetInbounds']();
}

export function GetKernelPath() {
  return window['go']['main']['App']['GetKernelPath']();
}

export function GetKernelStatus() {
  return window['go']['main']['App']['GetKernelStatus']();
}

export function GetNodeIPs(arg1) {
  return window['go']['main']['App']['GetNodeIPs'](arg1);
}

export function GetNodes() {
  return window['go']['main']['App']['GetNodes']();
}

export function GetProxySettings() {
  return window['go']['main']['App']['GetProxySettings']();
}

export function GetRoutingRules() {
  return window['go']['main']['App']['GetRoutingRules']();
}

export function GetTrafficStats() {
  return window['go']['main']['App']['GetTrafficStats']();
}

export function GetTransparentProxyConfig() {
  return window['go']['main']['App']['GetTransparentProxyConfig']();
}

export function ImportFromLink(arg1) {
  return window['go']['main']['App']['ImportFromLink'](arg1);
}

export function IsKernelInstalled() {
  return window['go']['main']['App']['IsKernelInstalled']();
}

export function IsProxyEnabled() {
  return window['go']['main']['App']['IsProxyEnabled']();
}

export function MoveNode(arg1, arg2) {
  return window['go']['main']['App']['MoveNode'](arg1, arg2);
}

export function OpenExternalURL(arg1) {
  return window['go']['main']['App']['OpenExternalURL'](arg1);
}

export function RemoveDNSServer(arg1) {
  return window['go']['main']['App']['RemoveDNSServer'](arg1);
}

export function ReorderRoutingRules(arg1) {
  return window['go']['main']['App']['ReorderRoutingRules'](arg1);
}

export function ResetTrafficStats() {
  return window['go']['main']['App']['ResetTrafficStats']();
}

export function RestartCore() {
  return window['go']['main']['App']['RestartCore']();
}

export function SelectFile(arg1, arg2) {
  return window['go']['main']['App']['SelectFile'](arg1, arg2);
}

export function SelectNode(arg1) {
  return window['go']['main']['App']['SelectNode'](arg1);
}

export function SetDNSConfig(arg1) {
  return window['go']['main']['App']['SetDNSConfig'](arg1);
}

export function SetProxySettings(arg1) {
  return window['go']['main']['App']['SetProxySettings'](arg1);
}

export function SetTransparentProxyConfig(arg1) {
  return window['go']['main']['App']['SetTransparentProxyConfig'](arg1);
}

export function StartCore() {
  return window['go']['main']['App']['StartCore']();
}

export function StopCore() {
  return window['go']['main']['App']['StopCore']();
}

export function TestAllNodesLatency() {
  return window['go']['main']['App']['TestAllNodesLatency']();
}

export function TestNodeLatency(arg1) {
  return window['go']['main']['App']['TestNodeLatency'](arg1);
}

export function ToggleInbound(arg1, arg2) {
  return window['go']['main']['App']['ToggleInbound'](arg1, arg2);
}

export function ToggleProxy() {
  return window['go']['main']['App']['ToggleProxy']();
}

export function UpdateInbound(arg1) {
  return window['go']['main']['App']['UpdateInbound'](arg1);
}

export function UpdateNode(arg1) {
  return window['go']['main']['App']['UpdateNode'](arg1);
}

export function UpdateRoutingRule(arg1) {
  return window['go']['main']['App']['UpdateRoutingRule'](arg1);
}
