// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function AddDNSServer(arg1:services.DNSServerItem):Promise<void>;

export function AddInbound(arg1:services.InboundRule):Promise<void>;

export function AddNode(arg1:services.ServerNode):Promise<void>;

export function AddRoutingRule(arg1:services.RoutingRule):Promise<void>;

export function ClearCoreLogs():Promise<void>;

export function CopyLogs(arg1:Array<string>):Promise<void>;

export function DeleteInbound(arg1:string):Promise<void>;

export function DeleteNode(arg1:string):Promise<void>;

export function DeleteRoutingRule(arg1:string):Promise<void>;

export function DisableProxy():Promise<void>;

export function DownloadKernel(arg1:string):Promise<void>;

export function EnableProxy():Promise<void>;

export function GenerateQRCode(arg1:string):Promise<string>;

export function GetActiveNodeID():Promise<string>;

export function GetAppVersion():Promise<string>;

export function GetCoreLogs(arg1:number):Promise<Array<string>>;

export function GetCoreStatus():Promise<string>;

export function GetCoreUptime():Promise<string>;

export function GetDNSConfig():Promise<services.DNSConfig>;

export function GetFilteredLogs(arg1:string,arg2:number):Promise<Array<string>>;

export function GetGroups():Promise<Array<services.ServerGroup>>;

export function GetInbounds():Promise<Array<services.InboundRule>>;

export function GetKernelPath():Promise<string>;

export function GetKernelStatus():Promise<Record<string, any>>;

export function GetNodeIPs(arg1:string):Promise<Array<string>>;

export function GetNodes():Promise<Array<services.ServerNode>>;

export function GetProxySettings():Promise<services.ProxySettings>;

export function GetRoutingRules():Promise<Array<services.RoutingRule>>;

export function GetTrafficStats():Promise<services.TrafficStats>;

export function GetTransparentProxyConfig():Promise<services.TransparentProxyConfig>;

export function ImportFromLink(arg1:string):Promise<services.ServerNode>;

export function IsKernelInstalled():Promise<boolean>;

export function IsProxyEnabled():Promise<boolean>;

export function MoveNode(arg1:string,arg2:string):Promise<void>;

export function OpenExternalURL(arg1:string):Promise<void>;

export function RemoveDNSServer(arg1:number):Promise<void>;

export function ReorderRoutingRules(arg1:Array<string>):Promise<void>;

export function ResetTrafficStats():Promise<void>;

export function RestartCore():Promise<void>;

export function SelectFile(arg1:string,arg2:string):Promise<string>;

export function SelectNode(arg1:string):Promise<void>;

export function SetDNSConfig(arg1:services.DNSConfig):Promise<void>;

export function SetProxySettings(arg1:services.ProxySettings):Promise<void>;

export function SetTransparentProxyConfig(arg1:services.TransparentProxyConfig):Promise<void>;

export function StartCore():Promise<void>;

export function StopCore():Promise<void>;

export function TestAllNodesLatency():Promise<Array<services.LatencyResult>>;

export function TestNodeLatency(arg1:string):Promise<services.LatencyResult>;

export function ToggleInbound(arg1:string,arg2:boolean):Promise<void>;

export function ToggleProxy():Promise<void>;

export function UpdateInbound(arg1:services.InboundRule):Promise<void>;

export function UpdateNode(arg1:services.ServerNode):Promise<void>;

export function UpdateRoutingRule(arg1:services.RoutingRule):Promise<void>;
